volumes:
  shared:

services:
  execution-client:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-reth:v2.3.1
    env_file:
      - .env
      # select your network here:
#      - .env.sepolia
#      - .env.mainnet
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 30303:30303/tcp
      - 30303:30303/udp
    volumes:
      - ${HOST_DATA_DIR}:/data
      - shared:/shared
      - ./op-reth-entrypoint.sh:/entrypoint.sh
    # healthcheck:
    #   start_interval: 5s
    #   start_period: 240s
    #   test: bash -c 'echo > /dev/tcp/localhost/8545'
    restart: always
    entrypoint: /entrypoint.sh

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.19.0
    env_file:
      - .env
      # select your network here:
#      - .env.sepolia
#      - .env.mainnet
    ports:
      - 9222:9222/udp
      - 9222:9222/tcp
      - 9545:9545/tcp
    volumes:
      - ${HOST_NODE_DATA_DIR}:/data
      - shared:/shared
    # healthcheck:
    #   start_interval: 5s
    #   start_period: 240s
    #   test: bash -c 'echo > /dev/tcp/localhost/9545'
    depends_on:
      execution-client:
        condition: service_healthy
    restart: always
